### PR TITLE
Added support to fire due Reminders

### PR DESCRIPTION
**Pull request by jonas-johansson**
Added support for telling the TestReminderRegistry what time it is and having it fire due reminders.

### CODE REVIEW

**Comment by seniorquico** [comment]
I'm trying to understand the use case for this change. Does the simple approach of firing the desired reminder by name not work? There's no need to mess around with `DateTime`s and date/time math with this approach:

```cs
await Silo.FireReminder(reminderName);
```

**Comment by jonas-johansson** [comment]
Hi seniorquico,

The idea is to be able to do black box testing where we don't need to know the internal implementation. Firing off the reminders, by name or all of them, disregards the aspect of the duration.

Imagine we make a grain that promises to do something in a certain amount of time. The way it accomplishes this is an implementation detail, all we care about is that it happens after time has passed. As a part of our testing framework we can then forward time by a specified amount and then observe the result.

**Comment by seniorquico** [comment]
> we don't need to know the internal implementation

The example grain in the test project illustrates a use case where the `TimeSpan`s passed as the reminder's `dueTime` and `period` are defined by the caller. For that use case, I can see how the date/time math may not be considered "internal implementation" of the grain. To be honest, I've never actually done that in a real system. I've always either used a constant value or calculated a `TimeSpan` within the grain in response to some event/method call. For my use cases, the date/time math is just as much "internal implementation" as the reminder name.

> Imagine we make a grain that promises to do something in a certain amount of time. The way it accomplishes this is an implementation detail, all we care about is that it happens after time has passed.

Not trying to be meta... but I'd caution against thinking that the TestKit or this PR will help you accomplish this goal. Namely, you can't exercise the grain using the TestKit without knowing the way it accomplishes that specific something. The test code is still coupled to an explicit call of `TestReminderRegistry`, and the fake clock is merely an alternative way to go about calling a grain method. It simply eliminates the need for a string literal reminder name.

I have two concerns with this change. First, it makes it difficult (impossible?) to isolate the invocation of multiple reminders. Let's take the following example grain:

```cs
public class ReportGrain : Grain, IReportGrain, IRemindable
{
    public async Task Schedule()
    {
        // Skipping calendar math for brevity...
        await this.RegisterOrUpdateReminder("weekly", TimeSpan.FromDays(7), TimeSpan.FromDays(7));
        await this.RegisterOrUpdateReminder("daily", TimeSpan.FromDays(1), TimeSpan.FromDays(1));
    }

    async Task IRemindable.ReceiveReminder(string reminderName, TickStatus status)
    {
        if (reminderName == "weekly")
        {
            ...
        }
        else if (reminderName == "daily")
        {
            ...
        }
    }
}
```

With `FireReminder`, I can have two separate tests that exercise my weekly and daily reminder routines in isolation. With this change, it doesn't appear to be possible to invoke the weekly reminder routine without also invoking the daily reminder routine:

```cs
[Fact]
public async Task Test()
{
    // Arrange
    var grain = await Silo.CreateGrainAsync<ReportGrain>(0);
    grain.Schedule();

    // Act -- fires both "weekly" and "daily" reminders!!!
    await Silo.ReminderRegistry.SetCurrentTime(DateTime.UtcNow.AddDays(7));

    // Assert
    ...
}
```

Second, it fails to identify some regressions. For example, let's consider the same `Test` method above with the following change to `ReportGrain`:

```diff
public async Task Schedule()
{
    // Skipping calendar math for brevity...
-    await this.RegisterOrUpdateReminder("weekly", TimeSpan.FromDays(7), TimeSpan.FromDays(7));
+    await this.RegisterOrUpdateReminder("weekly", TimeSpan.FromDays(10), TimeSpan.FromDays(10));
    await this.RegisterOrUpdateReminder("daily", TimeSpan.FromDays(1), TimeSpan.FromDays(1));
}
```

👍 The assertions in our `Test` method will catch this mistake as the "weekly" reminder routine does not fire.

But now consider the following change:

```diff
public async Task Schedule()
{
    // Skipping calendar math for brevity...
-    await this.RegisterOrUpdateReminder("weekly", TimeSpan.FromDays(7), TimeSpan.FromDays(7));
+    await this.RegisterOrUpdateReminder("weekly", TimeSpan.FromDays(5), TimeSpan.FromDays(5));
    await this.RegisterOrUpdateReminder("daily", TimeSpan.FromDays(1), TimeSpan.FromDays(1));
}
```

👎 The assertions in our `Test` method will not catch this mistake as the "weekly" reminder routine does fire.

The only way to (currently) assert the correct timespan is with the following:

```cs
Silo.ReminderRegistry.Mock.Verify(x => x.RegisterOrUpdateReminder(reminderName, dueTime, period));
```

But this means we still have a string literal reminder name in the test code, and we really haven't introduced the desired change of this PR.

I'm still amenable to this concept, though. Maybe some changes can alleviate the above concerns and make for a more robust API? Of note, I had considered brainstorming an API _just like this_ for the `TestTimerRegistry`. Unlike reminders, timers don't have a name. It's **very** awkward to fire reminders because they're identified by the order in which they were created. 😭 Now that's some serious coupling to implementation detail! 😉

And just to put it down for a "nice to have" wish list... I have been exploring areas where the TestKit behaviors differ from the Orleans runtime. Another gap in `TestReminderRegistry` is providing a `TickStatus` to the `ReceiveReminder` method. It would be great to see an improvement on that front.

**Comment by jonas-johansson** [comment]
Excuse the late reply!

Thanks for sharing the concerns, I see your worries. It might come down to test principles, and I'll try to to explain my view. 🙂

The goal is to make it possible to write tests where the following applies:
- We're not concerned with the internal implementation of the grain.
- We want to test that the observed result is equal to the expected result.
- We know that the grain depends on the Orleans framework, which provides services such as the reminder service (but this is not the test subject, it's part of the fixture).

The dependencies injected into the test subject need to fulfill their contracts - one of them being that the reminder service invokes reminders when time passes. Therefore, in tests where time is an ingredient, the test fixture should be arranged in such a way that time can pass and the dependencies behave the way they promise.

In the following example I don't know how it is implemented, but I know that we're working with time:
`
void AlarmRingTest()
{
	alarmGrain.ScheduleAlarm(TimeSpan.FromMinutes(3));
	alarmGrain.IsAlarmRinging.Should().BeFalse();
	testFixture.ForwardTime(TimeSpan.FromMinutes(3));
	alarmGrain.IsAlarmRinging.Should().BeTrue();
}
`

**Comment by jonas-johansson** [comment]
When testing from this perspective there's no end goal in isolating code paths inside the test subject. What's more important is to separate the tests though. One test for the daily and one for the weekly.

**Comment by seniorquico** [comment]
The TestKit attempts to provide a mock implementation of a grain activation context (and a partial implementation at that). It does not attempt to provide a mock implementation of an entire silo. Composing grain tests that require silo-level services are best accomplished with the [`TestCluster`](http://dotnet.github.io/orleans/Documentation/tutorials_and_samples/testing.html).

> The dependencies injected into the test subject need to fulfill their contracts - one of them being that the reminder service invokes reminders when time passes. Therefore, in tests where time is an ingredient, the test fixture should be arranged in such a way that time can pass and the dependencies behave the way they promise.

Grains only depend on the reminder registry (`IReminderRegistry`), they don't depend on the reminder service (`IReminderService`). The reminder registry simply manages the list of registered reminders, and in that context the current time is irrelevant. Your own test may view the subject as more than just the grain activation context, but that's not provided by the TestKit.

> In the following example I don't know how it is implemented, but I know that we're working with time:

Sorry, but you still have to know that the implementation is a reminder. How else do you cause the call to the `TestReminderRegistry.SetCurrentTime` method (as proposed by this PR)?

I still like your example-- the high-level API makes the test easy to read. I would suggest that, in the context of your example, the implementation of `testFixture` is a composition of the mock implementation of the grain activation context, a mock implementation of time, and a bridge between the two. If we keep all the time-related functionality in this bridge, it could be a generic solution for both reminders and timers. Additionally, it could be expanded to have a more robust API to generate different `TickStatus` values. For example, one could setup the `DateTime` a reminder "last fired" before invoking the time change.

The two previous concerns remain, and I think that's simply a downside of the proposed API. That may be acceptable for your use cases, but the docs should call out the limitations for new users. A new concern is that this may be construed as providing a mock implementation of the reminder service. Maybe it is, maybe it isn't. I think it could be presented as a utility class for use in fixtures. I would advocate we still document that it's not the goal of the TestKit to provide mock implementations of things outside the grain activation context. (And yes, docs are a long overdue task. 😢)

I'll try to work on some examples this evening.

**Pull request closed without merging**
