### PR TITLE
Added support of GetPrimaryKey

### PR DESCRIPTION
**Pull request by Ilchert**
Added support of GetPrimaryKey in GrainReference and IAddressable. #47, #73

### CODE REVIEW

**Comment by seniorquico** [comment]
It might take me a bit to review this. Off the cuff... I'm a bit concerned about the long-term maintenance of all the reflection magic. This library originally used lots of reflection magic to make things work (I don't recall if that was published to NuGet, it may have been our internally used bits before we were able to open source the library).

@dsarfati Do you recall injecting the `IActivationData`? What do you think of this reflection-based approach?

**Comment by Ilchert** [comment]
There is the only way to support `Grain.GrainReference` via reflection. We have already had some reflection and in short, this pull request just sets `Grain.Data` filed to properly configured `IActivationData` instance.

I did it to test my custom `GrainStorage`. It receives `GrainReference` as a parameter, but test grain hasn't set up `Grain.GrainReference` properly.

**Comment by Ilchert** [comment]
@seniorquico Any update here?

**Comment by Ilchert** [comment]
@seniorquico I am still here :)

**Comment by seniorquico** [comment]
This PR needs to be rebased and reopened against the `3.x` branch. Note- this issue has been fixed in version 4 and above the Orleans TestKit (which support Orleans 7+).

**Pull request closed without merging**
