### PR TITLE
Fix keyed services key type

### PR DESCRIPTION
**Pull request by rinkeb**
The type of the key in `AddKeyedService` is `string`, but should probably be `object?` to match `_keyedServices` and `GetKeyedService`. 

This allows for testing/mocking grain dependencies registered as a keyed service with another key type (for example `int`).

In addition, make the key param name consistent with `GetKeyedService` and `IKeyedServiceProvider`.

### CODE REVIEW

**Comment by seniorquico** [comment]
Thanks, @rinkeb! I'll clone it this weekend and run through some tests. Does this only affect Orleans 8 (not 7)?

**Comment by rinkeb** [comment]
Nice! 

_Does this only affect Orleans 8 (not 7)?_

Not sure. I started using the testkit just recently, already on Orleans 8. AFAIK keyed services keys have been of type `object?` since introduction in .net

**Comment by jkonecki** [comment]
I believe the regression issue with keyed services has been introduced in
.NET 8.

**Comment by seniorquico** [comment]
@rinkeb I added a few more overloads to facilitate keyed service registration and added some unit tests. Thanks!

**Pull request merged**
