### PR TITLE
Update to Orleans v1.4.2

### PR DESCRIPTION
**Pull request by wattsm**
Update to support Orleans v1.4.2.

### CODE REVIEW

**Comment by dsarfati** [comment]
@wattsm This looks great! Would you like to be added as an admin for this project. Unfortunately I'm not able to support it as much as I would like. Let me know and I can add you.

**Comment by wattsm** [comment]
@dsarfati Sure, I don't mind lending a hand :)

**Comment by sujesharukil** [comment]
Would it be worthwhile to branch and update to 1.5 instead?

**Comment by dsarfati** [comment]
@galvesribeiro Can you please add @wattsm? Not sure if this is something I can do or not.

**Comment by wattsm** [comment]
Superseded by #14, closing.

**Pull request closed without merging**
