### PR TITLE
Upgrade to rc2

### PR DESCRIPTION
**Pull request by AdamWyzgol**

### CODE REVIEW

**Comment by AdamWyzgol** [comment]
It's working on RC1 but fail on RC2

**Comment by AdamWyzgol** [comment]
fix for RC2

**Comment by dsarfati** [comment]
@AdamWyzgol Thanks for putting in the time to upgrade to the RC. With these changes do you think there are any additional tests that we need to add? It looks like most of these changes are internal impl details. 

Right now our tests are the only examples/docs on how to use the TestKit, so if we expose new features we have been trying to create matching tests.

**Comment by AdamWyzgol** [comment]
This version is sufficient for our project, if we need more features i submit issue or just send new pull request

**Pull request merged**
